version: '3.2'

services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:25.0
    command: "-fallbackfee=0.0002"
    volumes:
      - ./data/bitcoin:/srv/app/.bitcoin
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.9.14
    volumes:
      - ./data/electrs:/srv/app/db
    depends_on:
      - bitcoind
  proxy:
    image: ghcr.io/grunch/rgb-proxy-server:0.2.0
    ports:
      - 3000:3000
  jupyter:
    image: rgb-lib-python-demo
    build: .
    ports:
      - 8888:8888
    depends_on:
      - electrs
